### ISSUE TITLE
Ownership transfer

### ISSUE THREAD

**Issue by StephanvanSchaik** [elast0ny/dynamorio-sys#2]
Hi,

I am currently working on safe Rust bindings for DynamoRIO and thanks to your repository I am making pretty good progress on this:

- I am currently maintaining a fork of this repository [here](https://github.com/StephanvanSchaik/dynamorio-sys).
- I updated the crate to support DynamoRIO 9.0.0.
- I integrated cmake support into the build.rs such that you can either specify DRIO_BUILD_DIR to refer to an out-of-tree build of DynamoRIO or have Rust build DynamoRIO for you. This also works on Microsoft Windows.
- I have worked on a PR to DynamoRIO to [add support for MSVC 2019](https://github.com/DynamoRIO/dynamorio/pull/5274).
- I have added Linux support.
- I have a working DynamoRIO client written in Rust that I got to work on Linux, which initially was an issue due to segmentation faults caused by [the lack of a soname](https://github.com/rust-lang/cargo/issues/5045).

I am currently working on [dynamorio-rs](https://github.com/StephanvanSchaik/dynamorio-rs) to provide safe Rust bindings to dynamorio, as well as porting some of the examples over to make DynamoRIO in Rust more approachable.

In your README you indicated that you are willing transfer crate ownership to a more motivated developer, which is why I am asking if it is possible to transfer crate ownership so I can publish 9.0.0. I am also fine going with the PR route, if you are still willing to be the owner/maintainer of this crate :).

**Comment by elast0ny** [comment]
Hi, yes I took a look at your fork a few days ago ! 

I sent you an ownership invite on crates.io and can either give you write access to this repo or update my README to point to your repo if you want it under your github account :+1:

**Comment by StephanvanSchaik** [comment]
Thanks! I got and accepted the invite on crates.io. Write access to this repository would be fine with me too :).

**Comment by elast0ny** [comment]
Done !
